language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"

sudo: false

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test

after_success:
  - npm run coverage && npm run coveralls

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "8"
    - node_js: "7"
    - node_js: "6"
