version: 2.0

references:

  node13: &node13image
    docker:
      - image: circleci/node:13

  node13browser: &node13browsersimage
    docker:
      - image: circleci/node:13-browsers

  install_npm_default: &install_npm
    run: 
      name: Update npm
      command: 'sudo npm install -g npm@latest'

  restore_cache_default: &restore_cache # special step to restore the dependency cache
    restore_cache:
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        key: dependency-cache-{{ checksum "package.json" }}

  install_npm_packages_default: &install_npm_packages
    run:
        name: Install npm packages
        command: npm install

  save_cache_default: &save_cache # special step to save the dependency cache
    save_cache: 
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules

jobs:

  # Lint and Test

  lint_and_test_node_13: &lint_and_test
    <<: *node13image
    steps: 
      - checkout
      - *install_npm
      - *restore_cache
      - *install_npm_packages
      - *save_cache
      - run: &lint
          name: Lint
          command: yarn lint
      - run: &test
          name: Test
          command: yarn test

  # Pre-Release Test Integration

  pre_release_test_integration_node_13: &pre_release_test_integration
    <<: *node13browsersimage
    steps: 
      - checkout
      - *install_npm
      - *restore_cache
      - *install_npm_packages
      - *save_cache
      - run:
          name: Build browser tests and bundle
          command: ./integration-test/scripts/build-pre-release-test.sh
      - run:
          name: Test bundles
          command: |
            cd integration-test
            npm run test:pre-release

  # Post-Release Test Integration

  post_release_test_integration_node_13: &post_release_test_integration
    <<: *node13browsersimage
    steps: 
      - checkout
      - *install_npm
      - *restore_cache
      - *install_npm_packages
      - *save_cache
      - run:
          name: Build browser tests
          command: ./integration-test/scripts/build-post-release-test.sh
      - run:
          name: Test unpkg
          command: |
            cd integration-test
            npm run test:post-release

  npm_audit_node_13: &npm_audit
    docker:
      - image: circleci/golang:1.12.0-node
    steps: 
      - checkout
      - run: 
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install hub
          command: |
              set -xe
              go get -u -d github.com/github/hub
              cd /go/src/github.com/github/hub
              go install github.com/github/hub
      - run:
          name: Submit PR if npm audit fix makes changes
          command: ./scripts/npm-audit-fix.sh

workflows:
  version: 2
  test_all:
    jobs:
      - lint_and_test_node_13
      # - pre_release_test_integration_node_13
  nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
        # - npm_audit_node_13
        # - post_release_test_integration_node_13
