name: Lint and Test

# run CI on pushes to master, and on all PRs (even the ones that target other
# branches)

on: [push, pull_request]

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: node version
      run: node --version

    - name: cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn --frozen-lockfile

  lint:
    name: Lint
    needs: install
    steps:
    - run: yarn test

  test:
    name: Test
    needs: install
    steps:
    - run: yarn test
